export const categoriesMapping = {
  Book1: [
    { label: 'Lesson 1', link: '../json/B1 L1.json' },
    { label: 'Lesson 2', link: '../json/B1 L2.json' },
    { label: 'Lesson 3', link: '../json/B1 L3.json' },
    { label: 'Lesson 4', link: '../json/B1 L4.json' },
    { label: 'Lesson 5', link: '../json/B1 L5.json' },
    { label: 'Lesson 6', link: '../json/B1 L6.json' },
    { label: 'Lesson 7', link: '../json/B1 L7.json' },
    { label: 'Lesson 8', link: '../json/B1 L8.json' },
    { label: 'Lesson 9', link: '../json/B1 L9.json' },
    { label: 'Review 1', link: '../json/B1 review 1.json' },
    { label: 'Review 2', link: '../json/B1 review 2.json' },
    { label: 'Review 3', link: '../json/B1 review 3.json' },
  ],
  Book2: [
    { label: 'Lesson 1', link: '../json/B2 L1.json' },
    { label: 'Lesson 2', link: '../json/B2 L2.json' },
    { label: 'Lesson 3', link: '../json/B2 L3.json' },
    { label: 'Lesson 4', link: '../json/B2 L4.json' },
    { label: 'Lesson 5', link: '../json/B2 L5.json' },
    { label: 'Lesson 6', link: '../json/B2 L6.json' },
    { label: 'Lesson 7', link: '../json/B2 L7.json' },
    { label: 'Lesson 8', link: '../json/B2 L8.json' },
    { label: 'Lesson 9', link: '../json/B2 L9.json' },
    { label: 'Review 1', link: '../json/B2 review 1.json' },
    { label: 'Review 2', link: '../json/B2 review 2.json' },
    { label: 'Review 3', link: '../json/B2 review 3.json' },
  ],
  Book3: [
    { label: 'Lesson 1', link: '../json/B3 L1.json' },
    { label: 'Lesson 2', link: '../json/B3 L2.json' },
    { label: 'Lesson 3', link: '../json/B3 L3.json' },
    { label: 'Lesson 4', link: '../json/B3 L4.json' },
    { label: 'Lesson 5', link: '../json/B3 L5.json' },
    { label: 'Lesson 6', link: '../json/B3 L6.json' },
    { label: 'Lesson 7', link: '../json/B3 L7.json' },
    { label: 'Lesson 8', link: '../json/B3 L8.json' },
    { label: 'Lesson 9', link: '../json/B3 L9.json' },
    { label: 'Review 1', link: '../json/B3 review 1.json' },
    { label: 'Review 2', link: '../json/B3 review 2.json' },
    { label: 'Review 3', link: '../json/B3 review 3.json' },
  ],
  Book4: [
    { label: 'Lesson 1', link: '../json/B4 L1.json' },
    { label: 'Lesson 2', link: '../json/B4 L2.json' },
    { label: 'Lesson 3', link: '../json/B4 L3.json' },
    { label: 'Lesson 4', link: '../json/B4 L4.json' },
    { label: 'Lesson 5', link: '../json/B4 L5.json' },
    { label: 'Lesson 6', link: '../json/B4 L6.json' },
    { label: 'Lesson 7', link: '../json/B4 L7.json' },
    { label: 'Lesson 8', link: '../json/B4 L8.json' },
    { label: 'Lesson 9', link: '../json/B4 L9.json' },
    { label: 'Review 1', link: '../json/B4 review 1.json' },
    { label: 'Review 2', link: '../json/B4 review 2.json' },
    { label: 'Review 3', link: '../json/B4 review 3.json' },
  ],
  Book5: [
    { label: 'Lesson 1', link: '../json/B5 L1.json' },
    { label: 'Lesson 2', link: '../json/B5 L2.json' },
    { label: 'Lesson 3', link: '../json/B5 L3.json' },
    { label: 'Lesson 4', link: '../json/B5 L4.json' },
    { label: 'Lesson 5', link: '../json/B5 L5.json' },
    { label: 'Lesson 6', link: '../json/B5 L6.json' },
  ],
  '學測 7000 單': [
    { label: 'Level 1', link: '../json/Level 1.json' },
    { label: 'Level 2', link: '../json/Level 2.json' },
    { label: 'Level 3', link: '../json/Level 3.json' },
    { label: 'Level 4', link: '../json/Level 4.json' },
    { label: 'Level 5', link: '../json/Level 5.json' },
    { label: 'Level 6', link: '../json/Level 6.json' },
  ],
  '單字書 Level 2': [
    { label: 'Unit 1', link: '../json/vocabulary(L2 Unit1).json' },
    { label: 'Unit 2', link: '../json/vocabulary(L2 Unit2).json' },
    { label: 'Unit 3', link: '../json/vocabulary(L2 Unit3).json' },
    { label: 'Unit 4', link: '../json/vocabulary(L2 Unit4).json' },
    { label: 'Unit 5', link: '../json/vocabulary(L2 Unit5).json' },
    { label: 'Unit 6', link: '../json/vocabulary(L2 Unit6).json' },
    { label: 'Unit 7', link: '../json/vocabulary(L2 Unit7).json' },
    { label: 'Unit 8', link: '../json/vocabulary(L2 Unit8).json' },
  ],
  '單字書 Level 3': [
    { label: 'Unit 1', link: '../json/vocabulary(L3 Unit1).json' },
    { label: 'Unit 2', link: '../json/vocabulary(L3 Unit2).json' },
    { label: 'Unit 3', link: '../json/vocabulary(L3 Unit3).json' },
    { label: 'Unit 4', link: '../json/vocabulary(L3 Unit4).json' },
    { label: 'Unit 5', link: '../json/vocabulary(L3 Unit5).json' },
    { label: 'Unit 6', link: '../json/vocabulary(L3 Unit6).json' },
    { label: 'Unit 7', link: '../json/vocabulary(L3 Unit7).json' },
    { label: 'Unit 8', link: '../json/vocabulary(L3 Unit8).json' },
    { label: 'Unit 9', link: '../json/vocabulary(L3 Unit9).json' },
    { label: 'Unit 10', link: '../json/vocabulary(L3 Unit10).json' },
    { label: 'Unit 11', link: '../json/vocabulary(L3 Unit11).json' },
    { label: 'Unit 12', link: '../json/vocabulary(L3 Unit12).json' },
    { label: 'Unit 13', link: '../json/vocabulary(L3 Unit13).json' },
    { label: 'Unit 14', link: '../json/vocabulary(L3 Unit14).json' },
    { label: 'Unit 15', link: '../json/vocabulary(L3 Unit15).json' },
    { label: 'Unit 16', link: '../json/vocabulary(L3 Unit16).json' },
    { label: 'Unit 17', link: '../json/vocabulary(L3 Unit17).json' },
    { label: 'Unit 18', link: '../json/vocabulary(L3 Unit18).json' },
    { label: 'Unit 19', link: '../json/vocabulary(L3 Unit19).json' },
    { label: 'Unit 20', link: '../json/vocabulary(L3 Unit20).json' },
    { label: 'Unit 21', link: '../json/vocabulary(L3 Unit21).json' },
  ],
  '單字書 Level 4': [
    { label: 'Unit 1', link: '../json/vocabulary(L4 Unit1).json' },
    { label: 'Unit 2', link: '../json/vocabulary(L4 Unit2).json' },
    { label: 'Unit 3', link: '../json/vocabulary(L4 Unit3).json' },
    { label: 'Unit 4', link: '../json/vocabulary(L4 Unit4).json' },
    { label: 'Unit 5', link: '../json/vocabulary(L4 Unit5).json' },
    { label: 'Unit 6', link: '../json/vocabulary(L4 Unit6).json' },
    { label: 'Unit 7', link: '../json/vocabulary(L4 Unit7).json' },
    { label: 'Unit 8', link: '../json/vocabulary(L4 Unit8).json' },
    { label: 'Unit 9', link: '../json/vocabulary(L4 Unit9).json' },
    { label: 'Unit 10', link: '../json/vocabulary(L4 Unit10).json' },
    { label: 'Unit 11', link: '../json/vocabulary(L4 Unit11).json' },
    { label: 'Unit 12', link: '../json/vocabulary(L4 Unit12).json' },
    { label: 'Unit 13', link: '../json/vocabulary(L4 Unit13).json' },
    { label: 'Unit 14', link: '../json/vocabulary(L4 Unit14).json' },
    { label: 'Unit 15', link: '../json/vocabulary(L4 Unit15).json' },
    { label: 'Unit 16', link: '../json/vocabulary(L4 Unit16).json' },
    { label: 'Unit 17', link: '../json/vocabulary(L4 Unit17).json' },
    { label: 'Unit 18', link: '../json/vocabulary(L4 Unit18).json' },
    { label: 'Unit 19', link: '../json/vocabulary(L4 Unit19).json' },
    { label: 'Unit 20', link: '../json/vocabulary(L4 Unit20).json' },
    { label: 'Unit 21', link: '../json/vocabulary(L4 Unit21).json' },
  ],
  '常春藤 Level 5': [
    { label: 'Unit 1', link: '../json/vocabulary(L5 Unit1).json' },
    { label: 'Unit 2', link: '../json/vocabulary(L5 Unit2).json' },
    { label: 'Unit 3', link: '../json/vocabulary(L5 Unit3).json' },
    { label: 'Unit 4', link: '../json/vocabulary(L5 Unit4).json' },
    { label: 'Unit 5', link: '../json/vocabulary(L5 Unit5).json' },
    { label: 'Unit 6', link: '../json/vocabulary(L5 Unit6).json' },
    { label: 'Unit 7', link: '../json/vocabulary(L5 Unit7).json' },
    { label: 'Unit 8', link: '../json/vocabulary(L5 Unit8).json' },
    { label: 'Unit 9', link: '../json/vocabulary(L5 Unit9).json' },
    { label: 'Unit 10', link: '../json/vocabulary(L5 Unit10).json' },
    { label: 'Unit 11', link: '../json/vocabulary(L5 Unit11).json' },
    { label: 'Unit 12', link: '../json/vocabulary(L5 Unit12).json' },
    { label: 'Unit 13', link: '../json/vocabulary(L5 Unit13).json' },
    { label: 'Unit 14', link: '../json/vocabulary(L5 Unit14).json' },
    { label: 'Unit 15', link: '../json/vocabulary(L5 Unit15).json' },
    { label: 'Unit 16', link: '../json/vocabulary(L5 Unit16).json' },
    { label: 'Unit 17', link: '../json/vocabulary(L5 Unit17).json' },
    { label: 'Unit 18', link: '../json/vocabulary(L5 Unit18).json' },
    { label: 'Unit 19', link: '../json/vocabulary(L5 Unit19).json' },
    { label: 'Unit 20', link: '../json/vocabulary(L5 Unit20).json' },
    { label: 'Unit 21', link: '../json/vocabulary(L5 Unit21).json' },
    { label: 'Unit 22', link: '../json/vocabulary(L5 Unit22).json' },
    { label: 'Unit 23', link: '../json/vocabulary(L5 Unit23).json' },
    { label: 'Unit 24', link: '../json/vocabulary(L5 Unit24).json' },
    { label: 'Unit 25', link: '../json/vocabulary(L5 Unit25).json' },
  ],
  Allplus_Mar_2024: [
    { label: 'CNN News', link: '../json/ALL_PLUS_Mar_CNN_News.json' },
    { label: 'Unit 1', link: '../json/ALL_PLUS_Mar_Unit_1.json' },
    { label: 'Unit 2', link: '../json/ALL_PLUS_Mar_Unit_2.json' },
    { label: 'Unit 3', link: '../json/ALL_PLUS_Mar_Unit_3.json' },
    { label: 'Unit 4', link: '../json/ALL_PLUS_Mar_Unit_4.json' },
    { label: 'Unit 5', link: '../json/ALL_PLUS_Mar_Unit_5.json' },
    { label: 'Unit 6', link: '../json/ALL_PLUS_Mar_Unit_6.json' },
    { label: 'Unit 7', link: '../json/ALL_PLUS_Mar_Unit_7.json' },
    { label: 'Unit 9', link: '../json/ALL_PLUS_Mar_Unit_9.json' },
    { label: 'Unit 10', link: '../json/ALL_PLUS_Mar_Unit_10.json' },
    { label: 'Unit 11', link: '../json/ALL_PLUS_Mar_Unit_11.json' },
    { label: 'Unit 12', link: '../json/ALL_PLUS_Mar_Unit_12.json' },
    { label: 'Unit 13', link: '../json/ALL_PLUS_Mar_Unit_13.json' },
    { label: 'Unit 14', link: '../json/ALL_PLUS_Mar_Unit_14.json' },
    { label: 'Unit 15', link: '../json/ALL_PLUS_Mar_Unit_15.json' },
  ],
  Allplus_Apr_2024: [
    { label: 'CNN News', link: '../json/ALL_PLUS_Apr_CNN_News.json' },
    { label: 'Unit 1', link: '../json/ALL_PLUS_Apr_Unit_1.json' },
    { label: 'Unit 2', link: '../json/ALL_PLUS_Apr_Unit_2.json' },
    { label: 'Unit 3', link: '../json/ALL_PLUS_Apr_Unit_3.json' },
    { label: 'Unit 4', link: '../json/ALL_PLUS_Apr_Unit_4.json' },
    { label: 'Unit 5', link: '../json/ALL_PLUS_Apr_Unit_5.json' },
    { label: 'Unit 6', link: '../json/ALL_PLUS_Apr_Unit_6.json' },
    { label: 'Unit 8', link: '../json/ALL_PLUS_Apr_Unit_8.json' },
    { label: 'Unit 9', link: '../json/ALL_PLUS_Apr_Unit_9.json' },
    { label: 'Unit 10', link: '../json/ALL_PLUS_Apr_Unit_10.json' },
    { label: 'Unit 12', link: '../json/ALL_PLUS_Apr_Unit_12.json' },
    { label: 'Unit 13', link: '../json/ALL_PLUS_Apr_Unit_13.json' },
    { label: 'Unit 14', link: '../json/ALL_PLUS_Apr_Unit_14.json' },
    { label: 'Unit 15', link: '../json/ALL_PLUS_Apr_Unit_15.json' },
  ],
  Allplus_May_2024: [
    { label: 'Unit 1', link: '../json/ALL_PLUS_May_Unit_1.json' },
    { label: 'Unit 2', link: '../json/ALL_PLUS_May_Unit_2.json' },
    { label: 'Unit 3', link: '../json/ALL_PLUS_May_Unit_3.json' },
    { label: 'Unit 4', link: '../json/ALL_PLUS_May_Unit_4.json' },
    { label: 'Unit 5', link: '../json/ALL_PLUS_May_Unit_5.json' },
    { label: 'Unit 6', link: '../json/ALL_PLUS_May_Unit_6.json' },
    { label: 'Unit 7', link: '../json/ALL_PLUS_May_Unit_7.json' },
    { label: 'Unit 8', link: '../json/ALL_PLUS_May_Unit_8.json' },
    { label: 'Unit 10', link: '../json/ALL_PLUS_May_Unit_10.json' },
    { label: 'Unit 11', link: '../json/ALL_PLUS_May_Unit_11.json' },
    { label: 'Unit 12', link: '../json/ALL_PLUS_May_Unit_12.json' },
    { label: 'Unit 13', link: '../json/ALL_PLUS_May_Unit_13.json' },
    { label: 'Unit 14', link: '../json/ALL_PLUS_May_Unit_14.json' },
    { label: 'Unit 15', link: '../json/ALL_PLUS_May_Unit_15.json' },
    { label: 'Unit 16', link: '../json/ALL_PLUS_May_Unit_16.json' },
  ],
  Allplus_Jun_2024: [
    { label: 'CNN News', link: '../json/ALL_PLUS_Jun_CNN_News.json' },
    { label: 'Unit 1', link: '../json/ALL_PLUS_Jun_Unit_1.json' },
    { label: 'Unit 2', link: '../json/ALL_PLUS_Jun_Unit_2.json' },
    { label: 'Unit 3', link: '../json/ALL_PLUS_Jun_Unit_3.json' },
    { label: 'Unit 4', link: '../json/ALL_PLUS_Jun_Unit_4.json' },
    { label: 'Unit 5', link: '../json/ALL_PLUS_Jun_Unit_5.json' },
    { label: 'Unit 6', link: '../json/ALL_PLUS_Jun_Unit_6.json' },
    { label: 'Unit 7', link: '../json/ALL_PLUS_Jun_Unit_7.json' },
    { label: 'Unit 9', link: '../json/ALL_PLUS_Jun_Unit_9.json' },
    { label: 'Unit 10', link: '../json/ALL_PLUS_Jun_Unit_10.json' },
    { label: 'Unit 11', link: '../json/ALL_PLUS_Jun_Unit_11.json' },
    { label: 'Unit 12', link: '../json/ALL_PLUS_Jun_Unit_12.json' },
    { label: 'Unit 13', link: '../json/ALL_PLUS_Jun_Unit_13.json' },
    { label: 'Unit 14', link: '../json/ALL_PLUS_Jun_Unit_14.json' },
  ],
  Allplus_Sep_2024: [
    { label: 'Unit 1', link: '../json/ALL+ 2024 年 9 月號 Unit 1.json' },
    { label: 'Unit 2', link: '../json/ALL+ 2024 年 9 月號 Unit 2.json' },
    { label: 'Unit 3', link: '../json/ALL+ 2024 年 9 月號 Unit 3.json' },
    { label: 'Unit 4', link: '../json/ALL+ 2024 年 9 月號 Unit 4.json' },
    { label: 'Unit 5', link: '../json/ALL+ 2024 年 9 月號 Unit 5.json' },
    { label: 'Unit 6', link: '../json/ALL+ 2024 年 9 月號 Unit 6.json' },
    { label: 'Unit 8', link: '../json/ALL+ 2024 年 9 月號 Unit 8.json' },
    { label: 'Unit 9', link: '../json/ALL+ 2024 年 9 月號 Unit 9.json' },
    { label: 'Unit 10', link: '../json/ALL+ 2024 年 9 月號 Unit 10.json' },
    { label: 'Unit 11', link: '../json/ALL+ 2024 年 9 月號 Unit 11.json' },
    { label: 'Unit 12', link: '../json/ALL+ 2024 年 9 月號 Unit 12.json' },
    { label: 'Unit 13', link: '../json/ALL+ 2024 年 9 月號 Unit 13.json' },
    { label: 'CNN', link: '../json/ALL+ 2024 年 9 月號.json' }
  ],
  Allplus_Oct_2024: [
    { label: 'Unit 1', link: '../json/ALL+ 2024 年 10 月號 Unit 1.json' },
    { label: 'Unit 2', link: '../json/ALL+ 2024 年 10 月號 Unit 2.json' },
    { label: 'Unit 3', link: '../json/ALL+ 2024 年 10 月號 Unit 3.json' },
    { label: 'Unit 4', link: '../json/ALL+ 2024 年 10 月號 Unit 4.json' },
    { label: 'Unit 5', link: '../json/ALL+ 2024 年 10 月號 Unit 5.json' },
    { label: 'Unit 6', link: '../json/ALL+ 2024 年 10 月號 Unit 6.json' },
    { label: 'Unit 7', link: '../json/ALL+ 2024 年 10 月號 Unit 7.json' },
    { label: 'Unit 9', link: '../json/ALL+ 2024 年 10 月號 Unit 9.json' },
    { label: 'Unit 10', link: '../json/ALL+ 2024 年 10 月號 Unit 10.json' },
    { label: 'Unit 11', link: '../json/ALL+ 2024 年 10 月號 Unit 11.json' },
    { label: 'Unit 12', link: '../json/ALL+ 2024 年 10 月號 Unit 12.json' },
    { label: 'Unit 13', link: '../json/ALL+ 2024 年 10 月號 Unit 13.json' },
    { label: 'Unit 14', link: '../json/ALL+ 2024 年 10 月號 Unit 14.json' }
  ],
  Allplus_Nov_2024: [
    { label: 'Unit 1', link: '../json/ALL+ 2024 年 11 月號 Unit 1.json' },
    { label: 'Unit 2', link: '../json/ALL+ 2024 年 11 月號 Unit 2.json' },
    { label: 'Unit 3', link: '../json/ALL+ 2024 年 11 月號 Unit 3.json' },
    { label: 'Unit 4', link: '../json/ALL+ 2024 年 11 月號 Unit 4.json' },
    { label: 'Unit 5', link: '../json/ALL+ 2024 年 11 月號 Unit 5.json' },
    { label: 'Unit 7', link: '../json/ALL+ 2024 年 11 月號 Unit 7.json' },
    { label: 'Unit 8', link: '../json/ALL+ 2024 年 11 月號 Unit 8.json' },
    { label: 'Unit 9', link: '../json/ALL+ 2024 年 11 月號 Unit 9.json' },
    { label: 'Unit 10', link: '../json/ALL+ 2024 年 11 月號 Unit 10.json' },
    { label: 'Unit 11', link: '../json/ALL+ 2024 年 11 月號 Unit 11.json' },
    { label: 'Unit 12', link: '../json/ALL+ 2024 年 11 月號 Unit 12.json' },
    { label: 'Unit 13', link: '../json/ALL+ 2024 年 11 月號 Unit 13.json' },
    { label: 'CNN', link: '../json/ALL+ 2024 年 11 月號.json' }
  ],
  Allplus_Dec_2024: [
    { label: 'Unit 1', link: '../json/ALL+ 2024 年 12 月號 Unit 1.json' },
    { label: 'Unit 2', link: '../json/ALL+ 2024 年 12 月號 Unit 2.json' },
    { label: 'Unit 3', link: '../json/ALL+ 2024 年 12 月號 Unit 3.json' },
    { label: 'Unit 4', link: '../json/ALL+ 2024 年 12 月號 Unit 4.json' },
    { label: 'Unit 5', link: '../json/ALL+ 2024 年 12 月號 Unit 5.json' },
    { label: 'Unit 6', link: '../json/ALL+ 2024 年 12 月號 Unit 6.json' },
    { label: 'Unit 7', link: '../json/ALL+ 2024 年 12 月號 Unit 7.json' },
    { label: 'Unit 8', link: '../json/ALL+ 2024 年 12 月號 Unit 8.json' },
    { label: 'Unit 10', link: '../json/ALL+ 2024 年 12 月號 Unit 10.json' },
    { label: 'Unit 11', link: '../json/ALL+ 2024 年 12 月號 Unit 11.json' },
    { label: 'Unit 12', link: '../json/ALL+ 2024 年 12 月號 Unit 12.json' },
    { label: 'Unit 13', link: '../json/ALL+ 2024 年 12 月號 Unit 13.json' },
    { label: 'Unit 14', link: '../json/ALL+ 2024 年 12 月號 Unit 14.json' },
    { label: 'CNN', link: '../json/ALL+ 2024 年 12 月號.json' },
  ],
  Allplus_Jan_2025: [
    { label: 'Unit 1', link: '../json/ALL+ 2025 年 1 月號 Unit 1.json' },
    { label: 'Unit 2', link: '../json/ALL+ 2025 年 1 月號 Unit 2.json' },
    { label: 'Unit 3', link: '../json/ALL+ 2025 年 1 月號 Unit 3.json' },
    { label: 'Unit 4', link: '../json/ALL+ 2025 年 1 月號 Unit 4.json' },
    { label: 'Unit 5', link: '../json/ALL+ 2025 年 1 月號 Unit 5.json' },
    { label: 'Unit 6', link: '../json/ALL+ 2025 年 1 月號 Unit 6.json' },
    { label: 'Unit 7', link: '../json/ALL+ 2025 年 1 月號 Unit 7.json' },
    { label: 'Unit 9', link: '../json/ALL+ 2025 年 1 月號 Unit 9.json' },
    { label: 'Unit 10', link: '../json/ALL+ 2025 年 1 月號 Unit 10.json' },
    { label: 'Unit 11', link: '../json/ALL+ 2025 年 1 月號 Unit 11.json' },
    { label: 'Unit 12', link: '../json/ALL+ 2025 年 1 月號 Unit 12.json' },
    { label: 'Unit 13', link: '../json/ALL+ 2025 年 1 月號 Unit 13.json' },
    { label: 'Unit 14', link: '../json/ALL+ 2025 年 1 月號 Unit 14.json' },
    { label: 'CNN', link: '../json/ALL+ 2025 年 1 月號.json' }
  ],
  Allplus_Feb_2025: [
    { label: 'Unit 1', link: '../json/ALL+ 2025 年 2 月號 Unit 1.json' },
    { label: 'Unit 2', link: '../json/ALL+ 2025 年 2 月號 Unit 2.json' },
    { label: 'Unit 3', link: '../json/ALL+ 2025 年 2 月號 Unit 3.json' },
    { label: 'Unit 4', link: '../json/ALL+ 2025 年 2 月號 Unit 4.json' },
    { label: 'Unit 5', link: '../json/ALL+ 2025 年 2 月號 Unit 5.json' },
    { label: 'Unit 6', link: '../json/ALL+ 2025 年 2 月號 Unit 6.json' },
    { label: 'Unit 9', link: '../json/ALL+ 2025 年 2 月號 Unit 9.json' },
    { label: 'Unit 10', link: '../json/ALL+ 2025 年 2 月號 Unit 10.json' },
    { label: 'Unit 11', link: '../json/ALL+ 2025 年 2 月號 Unit 11.json' },
    { label: 'Unit 12', link: '../json/ALL+ 2025 年 2 月號 Unit 12.json' },
    { label: 'Unit 13', link: '../json/ALL+ 2025 年 2 月號 Unit 13.json' },
    { label: 'Unit 14', link: '../json/ALL+ 2025 年 2 月號 Unit 14.json' },
    { label: 'CNN', link: '../json/ALL+ 2025 年 2 月號.json' }
  ],
  Allplus_Mar_2025: [
    { label: 'Unit 1', link: '../json/ALL+ 2025 年 3 月號 Unit 1.json' },
    { label: 'Unit 2', link: '../json/ALL+ 2025 年 3 月號 Unit 2.json' },
    { label: 'Unit 3', link: '../json/ALL+ 2025 年 3 月號 Unit 3.json' },
    { label: 'Unit 4', link: '../json/ALL+ 2025 年 3 月號 Unit 4.json' },
    { label: 'Unit 5', link: '../json/ALL+ 2025 年 3 月號 Unit 5.json' },
    { label: 'Unit 7', link: '../json/ALL+ 2025 年 3 月號 Unit 7.json' },
    { label: 'Unit 8', link: '../json/ALL+ 2025 年 3 月號 Unit 8.json' },
    { label: 'Unit 9', link: '../json/ALL+ 2025 年 3 月號 Unit 9.json' },
    { label: 'Unit 10', link: '../json/ALL+ 2025 年 3 月號 Unit 10.json' },
    { label: 'Unit 11', link: '../json/ALL+ 2025 年 3 月號 Unit 11.json' },
    { label: 'Unit 12', link: '../json/ALL+ 2025 年 3 月號 Unit 12.json' },
    { label: 'Unit 13', link: '../json/ALL+ 2025 年 3 月號 Unit 13.json' },
    { label: 'Unit 14', link: '../json/ALL+ 2025 年 3 月號 Unit 14.json' },
    { label: 'Unit 15', link: '../json/ALL+ 2025 年 3 月號 Unit 15.json' },
    { label: 'CNN', link: '../json/ALL+ 2025 年 3 月號.json' }
  ],
  ivy_Sep_2024: [
    { label: '09-02', link: '../json/09-02_✶結合藝術與保育：水下雕塑公園_Undersea_Works_of_Art.json' },
    { label: '09-03', link: '../json/09-03_1._首見野生猩猩自製草藥敷傷口_2._聯合國：環保記者屢遭脅迫_1._Orangutan_Shows_Self-Healing_for_Wound_2.__Violence_towards_Environmental_Journalists_on_the_Rise.json' },
    { label: '09-04', link: '../json/09-04_母語忘光光！有可能嗎？_Losing_One’s_Mother_Tongue__The_Risk_of_Language_Attrition.json' },
    { label: '09-05', link: '../json/09-05_詞彙測驗_Vocabulary_Test_(2024.09).json' },
    { label: '09-06', link: '../json/09-06_敵不動我不動　鯨頭鸛怪怪惹人愛_The_Swamp’s_Silent_Hunter.json' },
    { label: '09-09', link: '../json/09-09_✶緊握扶手、站穩踏階……還有請勿行走？_Standing_on_the_Right_and_Passing_on_the_Left_.json' },
    { label: '09-10', link: '../json/09-10_遊客過度旅遊　居民苦不堪言_Overwhelmed_by_Overtourism【本篇為全程英文講解】.json' },
    { label: '09-11', link: '../json/09-11_✶泡泡啊，泡泡　你為什麼是圓的呢？_Why_Are_Bubbles_Round_.json' },
    { label: '09-12', link: '../json/09-12_活力早餐哪裡買？_Choosing_between_Freshness_and_Convenience.json' },
    { label: '09-13', link: '../json/09-13_✶「髓」緣之情　延續生命_Bone_Marrow_Transplants_Save_Lives.json' },
    { label: '09-16', link: '../json/09-16_城市中的救命旋律_The_Sound_that_Saves_Lives!.json' },
    { label: '09-17', link: '../json/09-17_古今消暑大作戰_Cooling_Hacks__Modern_vs_Ancient_Wisdom【本篇為全程英文講解】.json' },
    { label: '09-18', link: '../json/09-18_✶古今消暑大作戰_Cooling_Hacks__Modern_vs_Ancient_Wisdom【本篇為全程英文講解】.json' },
    { label: '09-19', link: '../json/09-19_來自地球的致意_跨越星河的忠告__A_Message_across_the_Milky_Way.json' },
    { label: '09-20', link: '../json/09-20_花蓮風景美如畫_自然歷史大會串_Hualien__A_Marvel_of_Natural_Beauty_and_Cultural_History.json' },
    { label: '09-23', link: '../json/09-23_掉落食物秒撿起？_細菌笑你太天真！Five_Seconds_Don’t_Save_Food.json' },
    { label: '09-24', link: '../json/09-24_翻譯_Translation_(2024.09).json' },
    { label: '09-25', link: '../json/09-25_50_分貝：_最健康的噪音強度！Finding_the_Sweet_Spot_for_Office_Noise.json' },
    { label: '09-26', link: '../json/09-26_你的睡眠像哪種動物？_Sleep_Chronotypes__Which_Animal_Are_You_.json' },
    { label: '09-27', link: '../json/09-27_你的睡眠像哪種動物？_Sleep_Chronotypes__Which_Animal_Are_You_.json' },
    { label: '09-30', link: '../json/09-30_解析文法【動詞_-_1】.json' }
  ],
  ivy_Oct_2024: [
    { label: '10-01', link: '../json/10-01_✶科技看見你的聲音_Hear_through_Your_Eyes__TranscribeGlass.json' },
    { label: '10-02', link: '../json/10-02_1._藍綠屋頂：城市裡的大海綿！_2._動保新篇章：哥倫比亞立法禁鬥牛.json' },
    { label: '10-03', link: '../json/10-03_詞彙測驗_Vocabulary_Test_(2024.10).json' },
    { label: '10-04', link: '../json/10-04_獨角鯨的探海神針：螺旋牙_The_Unicorns_of_the_Sea.json' },
    { label: '10-07', link: '../json/10-07_俯瞰布拉格廣場：歷史悠久的天文鐘_Prague’s_Astronomical_Clock_Is_Out_of_This_World.json' },
    { label: '10-08', link: '../json/10-08_首位被鑄在美國硬幣上的亞裔人：黃柳霜_Anna_May_Wong__A_Hollywood_Legend.json' },
    { label: '10-09', link: '../json/10-09_✶美國科州簽署法案_保護腦波隱私_Colorado_Becomes_First_State_to_Pass_Brainwave_Privacy_Law.json' },
    { label: '10-10', link: '../json/10-10_✶地震來了怎知道？手機「劇透」報你知_Understanding_Earthquake_Early_Warning_Systems.json' },
    { label: '10-11', link: '../json/10-11_解析文法【動詞_-_2】.json' },
    { label: '10-14', link: '../json/10-14_原來動物都不愛白吃的午餐！呃……喵星人除外_Contra-Freeloading__The_Work-for-Food_Phenomenon_in_Nature.json' },
    { label: '10-15', link: '../json/10-15_✶日隱月現_夜幕天降_Eclipsing_the_Ordinary___A_Moment_under_the_Moon’s_Shadow.json' },
    { label: '10-16', link: '../json/10-16_日隱月現_夜幕天降_Eclipsing_the_Ordinary___A_Moment_under_the_Moon’s_Shadow.json' },
    { label: '10-17', link: '../json/10-17_化悲傷為力量_Turning_a_Painful_Setback_into__a_Valuable_Life_Lesson.json' },
    { label: '10-18', link: '../json/10-18_二手難題：雙贏的局面有問題？_The_Unseen_Impact_of_Secondhand_Clothing.json' },
    { label: '10-21', link: '../json/10-21_肉桂香甜蜜蜜_捲到幸福滿溢_Cinnamon_and_the_Timeless_Treat_of__the_Cinnamon_Roll.json' },
    { label: '10-22', link: '../json/10-22_食安警鐘響起，遠離毒害預備～起！After_Restaurant_Sickness.json' },
    { label: '10-23', link: '../json/10-23_古今輝映「彰」顯魅力_Changhua__Explore_the_Culture_and_Natural_Beauty_of_Central_Taiwan.json' },
    { label: '10-24', link: '../json/10-24_無用器官真的無用嗎？_Are_These_Organs_Really_Useless_.json' },
    { label: '10-25', link: '../json/10-25_無用器官真的無用嗎？_Are_These_Organs_Really_Useless_.json' },
    { label: '10-28', link: '../json/10-28_新車為什麼好好聞？_The_Science_and_Psychology_of_the_New_Car_Smell.json' },
    { label: '10-29', link: '../json/10-29_翻譯_Translation_(2024.10).json' },
    { label: '10-30', link: '../json/10-30_1._涉及的範圍很廣__2._跌到谷底.json' },
    { label: '10-31', link: '../json/10-31_解析文法【動詞_-_3】.json' }
  ],
  ivy_Nov_2024: [
    { label: '11-01', link: '../json/11-01_詞彙測驗_Vocabulary_Test_(2024.11).json' },
    { label: '11-04', link: '../json/11-04_✶短暫的相遇_也能是一條救命繩索__Life-Saving_Power_of_Chance_Meetings.json' },
    { label: '11-05', link: '../json/11-05_翻譯_Translation_(2024.11).json' },
    { label: '11-06', link: '../json/11-06_陽光灑落指尖_慢遊美麗屏東_Taiwan’s_Tropical_Paradise_of_Pingtung.json' },
    { label: '11-07', link: '../json/11-07_高中同學會_地點怎麼選？_Choosing_the_Perfect_Venue_for_a_High_School_Reunion.json' },
    { label: '11-08', link: '../json/11-08_✶非洲水牛懂投票_牛牛的草原民主_African_Buffalo__The_Democratic_Diners【本篇為全程英文講解】.json' },
    { label: '11-11', link: '../json/11-11_✶喝茶也會醉？_Becoming_Tea_Drunk.json' },
    { label: '11-12', link: '../json/11-12_論文造假暴增！逾萬篇論文遭撤回_Publishing_Company_Shuts_Down_19_Publications_amidst_an_Increase_in_Paper_Mills.json' },
    { label: '11-13', link: '../json/11-13_這裡癢那裡也癢_抓一抓就不癢了嗎？_Scratch_That_Itch.json' },
    { label: '11-14', link: '../json/11-14_收到借錢訊息？小心有詐！_Falling_Victim_to_a_LINE_Scam.json' },
    { label: '11-15', link: '../json/11-15_✶璀璨的玫瑰窗：光影映射下的宗教藝術__The_Rose_Window_of_Medieval_Europe.json' },
    { label: '11-18', link: '../json/11-18_社群狂曬美食照　這樣好嗎？好嗎？_Food_for_Thought__Is_Foodstagramming_Healthy_.json' },
    { label: '11-19', link: '../json/11-19_裙撐：撐起美麗的一片天_The_Hoop_Skirt__Balancing_High_Fashion_with_Comfort_and_Ease_of_Use.json' },
    { label: '11-20', link: '../json/11-20_裙撐：撐起美麗的一片天_The_Hoop_Skirt__Balancing_High_Fashion_with_Comfort_and_Ease_of_Use.json' },
    { label: '11-21', link: '../json/11-21_1._該某人行動了__2._曝光_被揭露_為人所知.json' },
    { label: '11-22', link: '../json/11-22_✶從_F4_到_F1_賽場角逐多激昂_The_Road_to_F1.json' },
    { label: '11-25', link: '../json/11-25_鳥籠陷阱要警惕　慾望束縛轉助力__The_Birdcage_Dilemma.json' },
    { label: '11-26', link: '../json/11-26_神奇馬賽皂_天然ㄟ尚好_The_Timeless_Legacy_of_Marseille_Soap【本篇為全程英文講解】.json' },
    { label: '11-27', link: '../json/11-27_神奇馬賽皂_天然ㄟ尚好_The_Timeless_Legacy_of_Marseille_Soap【本篇為全程英文講解】.json' },
    { label: '11-28', link: '../json/11-28_善用「我」訊息　溝通不窒息_Turn_“You”_into_“I”_and_Watch_Your_Relationships_Thrive.json' },
    { label: '11-29', link: '../json/11-29_解析文法【動詞_-_4】.json' }
  ],
  ivy_Dec_2024: [
    { label: '12-02', link: '../json/12-02_吃到剛剛好_健康煩惱少_The_Secret_Eating_Style_to_a_Long_Life.json' },
    { label: '12-03', link: '../json/12-03_1._飛機起降排放影響千萬人健康__2.解謎澳洲！史前「牛頓巨鳥」頭骨問世.json' },
    { label: '12-04', link: '../json/12-04_德國北海海底的遠古建築：閃耀千年的石牆_The_Discovery_of_Europe’s_Oldest_Known_Megastructure__The_Blinkerwall.json' },
    { label: '12-05', link: '../json/12-05_詞彙測驗_Vocabulary_Test_(2024.12).json' },
    { label: '12-06', link: '../json/12-06_✶超級偽裝大師：石頭魚__Stonefish__The_Most_Unassuming_Sea_Creature.json' },
    { label: '12-09', link: '../json/12-09_震撼森林：揭開地震對樹木恢復的長期影響_Beyond_the_Tremors__Unveiling_the_Long-Term_Impact_of_Earthquakes_on_Forests.json' },
    { label: '12-10', link: '../json/12-10_✶深海發現暗氧　產氧無須光合作用_Dark_Oxygen_Found_in_Ocean_Depths_without_Light.json' },
    { label: '12-11', link: '../json/12-11_維修權_UP！廢棄物_DOWN_Repairability_Indexes_Support_Sustainability.json' },
    { label: '12-12', link: '../json/12-12_社群媒體上的主題標籤濫用_The_Misuse_of_Hashtags_on_Social_Media.json' },
    { label: '12-13', link: '../json/12-13_✶街燈千年演變：從古老竹燈到先進_LED_The_Bright_Past_and_Future_of_Street_Lights【全程英文講解】.json' },
    { label: '12-16', link: '../json/12-16_✶對抗單車賊　「臭鼬鎖」的逆襲_SKUNKLOCK__The_Bike_Lock_That_Fights_Back.json' },
    { label: '12-17', link: '../json/12-17_旋轉_跳躍_溜溜球不停歇_The_Yo-Yo__A_Classic_Toy_for_Any_Age.json' },
    { label: '12-18', link: '../json/12-18_旋轉_跳躍_溜溜球不停歇_The_Yo-Yo__A_Classic_Toy_for_Any_Age.json' },
    { label: '12-19', link: '../json/12-19_選擇電信公司的優先考量_Key_Factors_to_Consider_When_Choosing__a_Telecommunications_Company.json' },
    { label: '12-20', link: '../json/12-20_聖誕浪漫物語：槲寄生下的吻_Making_Merry_under_the_Mistletoe.json' },
    { label: '12-23', link: '../json/12-23_✶古今戲院_紅色不變_Why_Red__The_Story_behind_Theater_Seats.json' },
    { label: '12-24', link: '../json/12-24_翻譯_Translation_(2024.12).json' },
    { label: '12-25', link: '../json/12-25_南投冬之旅_景等著你__Immerse_Yourself_in_Nantou’s_Winter_Wonderland【全程英文講解】.json' },
    { label: '12-26', link: '../json/12-26_南投冬之旅_美景等著你__Immerse_Yourself_in_Nantou’s_Winter_Wonderland【全程英文講解】.json' },
    { label: '12-27', link: '../json/12-27_1._大人物，要人__2._最重要的點.json' },
    { label: '12-30', link: '../json/12-30_當熟悉突然變陌生｜大腦「從未見過」現象_Jamais_Vu__The_Phenomenon_of_Never_Seen.json' },
    { label: '12-31', link: '../json/12-31_解析文法【動詞_-_5】.json' }
  ]
};

export const loadCategoryData = async (category, subcategory) => {
  try {
    const subItem = categoriesMapping[category]?.find(
      (s) => s.label === subcategory
    );

    if (!subItem?.link) {
      throw new Error('Category or subcategory not found');
    }

    const response = await fetch(subItem.link);
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }

    const data = await response.json();
    return data;
  } catch (error) {
    console.error('Error loading category data:', error);
    return null;
  }
};

export const updateCategoryMapping = (newCategory, subcategories) => {
  if (!categoriesMapping[newCategory]) {
    categoriesMapping[newCategory] = [];
  }

  subcategories.forEach(sub => {
    if (!categoriesMapping[newCategory].find(item => item.label === sub.label)) {
      categoriesMapping[newCategory].push(sub);
    }
  });
};

export const removeCategoryMapping = (category, subcategoryLabel = null) => {
  if (subcategoryLabel) {
    if (categoriesMapping[category]) {
      categoriesMapping[category] = categoriesMapping[category].filter(
        sub => sub.label !== subcategoryLabel
      );
    }
  } else {
    delete categoriesMapping[category];
  }
};