export const categoriesMapping = {
    Book1: [
        { label: 'Lesson 1', link: '../json/B1 L1.json'},
        { label: 'Lesson 2', link: '../json/B1 L2.json'},
        { label: 'Lesson 3', link: '../json/B1 L3.json'},
        { label: 'Lesson 4', link: '../json/B1 L4.json'},
        { label: 'Lesson 5', link: '../json/B1 L5.json'},
        { label: 'Lesson 6', link: '../json/B1 L6.json'},
        { label: 'Lesson 7', link: '../json/B1 L7.json'},
        { label: 'Lesson 8', link: '../json/B1 L8.json'},
        { label: 'Lesson 9', link: '../json/B1 L9.json'},
        { label: 'Review 1', link: '../json/B1 review 1.json'},
        { label: 'Review 2', link: '../json/B1 review 2.json'},
        { label: 'Review 3', link: '../json/B1 review 3.json'},
    ],
    Book2: [
        { label: 'Lesson 1', link: '../json/B2 L1.json'},
        { label: 'Lesson 2', link: '../json/B2 L2.json'},
        { label: 'Lesson 3', link: '../json/B2 L3.json'},
        { label: 'Lesson 4', link: '../json/B2 L4.json'},
        { label: 'Lesson 5', link: '../json/B2 L5.json'},
        { label: 'Lesson 6', link: '../json/B2 L6.json'},
        { label: 'Lesson 7', link: '../json/B2 L7.json'},
        { label: 'Lesson 8', link: '../json/B2 L8.json'},
        { label: 'Lesson 9', link: '../json/B2 L9.json'},
        { label: 'Review 1', link: '../json/B2 review 1.json'},
        { label: 'Review 2', link: '../json/B2 review 2.json'},
        { label: 'Review 3', link: '../json/B2 review 3.json'},
    ],
    Book3: [
        { label: 'Lesson 1', link: '../json/B3 L1.json'},
        { label: 'Lesson 2', link: '../json/B3 L2.json'},
        { label: 'Lesson 3', link: '../json/B3 L3.json'},
        { label: 'Lesson 4', link: '../json/B3 L4.json'},
        { label: 'Lesson 5', link: '../json/B3 L5.json'},
        { label: 'Lesson 6', link: '../json/B3 L6.json'},
        { label: 'Lesson 7', link: '../json/B3 L7.json'},
        { label: 'Lesson 8', link: '../json/B3 L8.json'},
        { label: 'Lesson 9', link: '../json/B3 L9.json'},
        { label: 'Review 1', link: '../json/B3 review 1.json'},
        { label: 'Review 2', link: '../json/B3 review 2.json'},
        { label: 'Review 3', link: '../json/B3 review 3.json'},
    ],
    Book4: [
        { label: 'Lesson 1', link: '../json/B4 L1.json'},
        { label: 'Lesson 2', link: '../json/B4 L2.json'},
        { label: 'Lesson 3', link: '../json/B4 L3.json'},
        { label: 'Lesson 4', link: '../json/B4 L4.json'},
        { label: 'Lesson 5', link: '../json/B4 L5.json'},
        { label: 'Lesson 6', link: '../json/B4 L6.json'},
        { label: 'Lesson 7', link: '../json/B4 L7.json'},
        { label: 'Lesson 8', link: '../json/B4 L8.json'},
        { label: 'Lesson 9', link: '../json/B4 L9.json'},
        { label: 'Review 1', link: '../json/B4 review 1.json'},
        { label: 'Review 2', link: '../json/B4 review 2.json'},
        { label: 'Review 3', link: '../json/B4 review 3.json'},
    ],
    Book5: [
        { label: 'Lesson 1', link: '../json/B5 L1.json'},
        { label: 'Lesson 2', link: '../json/B5 L2.json'},
        { label: 'Lesson 3', link: '../json/B5 L3.json'},
        { label: 'Lesson 4', link: '../json/B5 L4.json'},
        { label: 'Lesson 5', link: '../json/B5 L5.json'},
        { label: 'Lesson 6', link: '../json/B5 L6.json'},
    ],
    '學測 7000 單': [
        { label: 'Level 1', link: '../json/Level 1.json'},
        { label: 'Level 2', link: '../json/Level 2.json'},
        { label: 'Level 3', link: '../json/Level 3.json'},
        { label: 'Level 4', link: '../json/Level 4.json'},
        { label: 'Level 5', link: '../json/Level 5.json'},
        { label: 'Level 6', link: '../json/Level 6.json'},
    ],
    '單字書 Level 2': [
        { label: 'Unit 1', link: '../json/vocabulary(L2 Unit1).json'},
        { label: 'Unit 2', link: '../json/vocabulary(L2 Unit2).json'},
        { label: 'Unit 3', link: '../json/vocabulary(L2 Unit3).json'},
        { label: 'Unit 4', link: '../json/vocabulary(L2 Unit4).json'},
        { label: 'Unit 5', link: '../json/vocabulary(L2 Unit5).json'},
        { label: 'Unit 6', link: '../json/vocabulary(L2 Unit6).json'},
        { label: 'Unit 7', link: '../json/vocabulary(L2 Unit7).json'},
        { label: 'Unit 8', link: '../json/vocabulary(L2 Unit8).json'},
    ],
    '單字書 Level 3': [
        { label: 'Unit 1', link: '../json/vocabulary(L3 Unit1).json'},
        { label: 'Unit 2', link: '../json/vocabulary(L3 Unit2).json'},
        { label: 'Unit 3', link: '../json/vocabulary(L3 Unit3).json'},
        { label: 'Unit 4', link: '../json/vocabulary(L3 Unit4).json'},
        { label: 'Unit 5', link: '../json/vocabulary(L3 Unit5).json'},
        { label: 'Unit 6', link: '../json/vocabulary(L3 Unit6).json'},
        { label: 'Unit 7', link: '../json/vocabulary(L3 Unit7).json'},
        { label: 'Unit 8', link: '../json/vocabulary(L3 Unit8).json'},
        { label: 'Unit 9', link: '../json/vocabulary(L3 Unit9).json'},
        { label: 'Unit 10', link: '../json/vocabulary(L3 Unit10).json'},
        { label: 'Unit 11', link: '../json/vocabulary(L3 Unit11).json'},
        { label: 'Unit 12', link: '../json/vocabulary(L3 Unit12).json'},
        { label: 'Unit 13', link: '../json/vocabulary(L3 Unit13).json'},
        { label: 'Unit 14', link: '../json/vocabulary(L3 Unit14).json'},
        { label: 'Unit 15', link: '../json/vocabulary(L3 Unit15).json'},
        { label: 'Unit 16', link: '../json/vocabulary(L3 Unit16).json'},
        { label: 'Unit 17', link: '../json/vocabulary(L3 Unit17).json'},
        { label: 'Unit 18', link: '../json/vocabulary(L3 Unit18).json'},
        { label: 'Unit 19', link: '../json/vocabulary(L3 Unit19).json'},
        { label: 'Unit 20', link: '../json/vocabulary(L3 Unit20).json'},
        { label: 'Unit 21', link: '../json/vocabulary(L3 Unit21).json'},
    ],
    '單字書 Level 4': [
        { label: 'Unit 1', link: '../json/vocabulary(L4 Unit1).json'},
        { label: 'Unit 2', link: '../json/vocabulary(L4 Unit2).json'},
        { label: 'Unit 3', link: '../json/vocabulary(L4 Unit3).json'},
        { label: 'Unit 4', link: '../json/vocabulary(L4 Unit4).json'},
        { label: 'Unit 5', link: '../json/vocabulary(L4 Unit5).json'},
        { label: 'Unit 6', link: '../json/vocabulary(L4 Unit6).json'},
        { label: 'Unit 7', link: '../json/vocabulary(L4 Unit7).json'},
        { label: 'Unit 8', link: '../json/vocabulary(L4 Unit8).json'},
        { label: 'Unit 9', link: '../json/vocabulary(L4 Unit9).json'},
        { label: 'Unit 10', link: '../json/vocabulary(L4 Unit10).json'},
        { label: 'Unit 11', link: '../json/vocabulary(L4 Unit11).json'},
        { label: 'Unit 12', link: '../json/vocabulary(L4 Unit12).json'},
        { label: 'Unit 13', link: '../json/vocabulary(L4 Unit13).json'},
        { label: 'Unit 14', link: '../json/vocabulary(L4 Unit14).json'},
        { label: 'Unit 15', link: '../json/vocabulary(L4 Unit15).json'},
        { label: 'Unit 16', link: '../json/vocabulary(L4 Unit16).json'},
        { label: 'Unit 17', link: '../json/vocabulary(L4 Unit17).json'},
        { label: 'Unit 18', link: '../json/vocabulary(L4 Unit18).json'},
        { label: 'Unit 19', link: '../json/vocabulary(L4 Unit19).json'},
        { label: 'Unit 20', link: '../json/vocabulary(L4 Unit20).json'},
        { label: 'Unit 21', link: '../json/vocabulary(L4 Unit21).json'},
    ],
    '常春藤 Level 5': [
        { label: 'Unit 1', link: '../json/vocabulary(L5 Unit1).json'},
        { label: 'Unit 2', link: '../json/vocabulary(L5 Unit2).json'},
        { label: 'Unit 3', link: '../json/vocabulary(L5 Unit3).json'},
        { label: 'Unit 4', link: '../json/vocabulary(L5 Unit4).json'},
        { label: 'Unit 5', link: '../json/vocabulary(L5 Unit5).json'},
        { label: 'Unit 6', link: '../json/vocabulary(L5 Unit6).json'},
        { label: 'Unit 7', link: '../json/vocabulary(L5 Unit7).json'},
        { label: 'Unit 8', link: '../json/vocabulary(L5 Unit8).json'},
        { label: 'Unit 9', link: '../json/vocabulary(L5 Unit9).json'},
        { label: 'Unit 10', link: '../json/vocabulary(L5 Unit10).json'},
        { label: 'Unit 11', link: '../json/vocabulary(L5 Unit11).json'},
        { label: 'Unit 12', link: '../json/vocabulary(L5 Unit12).json'},
        { label: 'Unit 13', link: '../json/vocabulary(L5 Unit13).json'},
        { label: 'Unit 14', link: '../json/vocabulary(L5 Unit14).json'},
        { label: 'Unit 15', link: '../json/vocabulary(L5 Unit15).json'},
        { label: 'Unit 16', link: '../json/vocabulary(L5 Unit16).json'},
        { label: 'Unit 17', link: '../json/vocabulary(L5 Unit17).json'},
        { label: 'Unit 18', link: '../json/vocabulary(L5 Unit18).json'},
        { label: 'Unit 19', link: '../json/vocabulary(L5 Unit19).json'},
        { label: 'Unit 20', link: '../json/vocabulary(L5 Unit20).json'},
        { label: 'Unit 21', link: '../json/vocabulary(L5 Unit21).json'},
        { label: 'Unit 22', link: '../json/vocabulary(L5 Unit22).json'},
        { label: 'Unit 23', link: '../json/vocabulary(L5 Unit23).json'},
        { label: 'Unit 24', link: '../json/vocabulary(L5 Unit24).json'},
        { label: 'Unit 25', link: '../json/vocabulary(L5 Unit25).json'},
    ],
    ALL_PLUS_Mar: [
      { label: 'CNN News', link: '../json/ALL_PLUS_Mar_CNN_News.json' },
      { label: 'Unit 1', link: '../json/ALL_PLUS_Mar_Unit_1.json' },
      { label: 'Unit 2', link: '../json/ALL_PLUS_Mar_Unit_2.json' },
      { label: 'Unit 3', link: '../json/ALL_PLUS_Mar_Unit_3.json' },
      { label: 'Unit 4', link: '../json/ALL_PLUS_Mar_Unit_4.json' },
      { label: 'Unit 5', link: '../json/ALL_PLUS_Mar_Unit_5.json' },
      { label: 'Unit 6', link: '../json/ALL_PLUS_Mar_Unit_6.json' },
      { label: 'Unit 7', link: '../json/ALL_PLUS_Mar_Unit_7.json' },
      { label: 'Unit 9', link: '../json/ALL_PLUS_Mar_Unit_9.json' },
      { label: 'Unit 10', link: '../json/ALL_PLUS_Mar_Unit_10.json' },
      { label: 'Unit 11', link: '../json/ALL_PLUS_Mar_Unit_11.json' },
      { label: 'Unit 12', link: '../json/ALL_PLUS_Mar_Unit_12.json' },
      { label: 'Unit 13', link: '../json/ALL_PLUS_Mar_Unit_13.json' },
      { label: 'Unit 14', link: '../json/ALL_PLUS_Mar_Unit_14.json' },
      { label: 'Unit 15', link: '../json/ALL_PLUS_Mar_Unit_15.json' },
    ],
    ALL_PLUS_Apr: [
        { label: 'CNN News', link: '../json/ALL_PLUS_Apr_CNN_News.json'},
        { label: 'Unit 1', link: '../json/ALL_PLUS_Apr_Unit_1.json'},
        { label: 'Unit 2', link: '../json/ALL_PLUS_Apr_Unit_2.json'},
        { label: 'Unit 3', link: '../json/ALL_PLUS_Apr_Unit_3.json'},
        { label: 'Unit 4', link: '../json/ALL_PLUS_Apr_Unit_4.json'},
        { label: 'Unit 5', link: '../json/ALL_PLUS_Apr_Unit_5.json'},
        { label: 'Unit 6', link: '../json/ALL_PLUS_Apr_Unit_6.json'},
        { label: 'Unit 8', link: '../json/ALL_PLUS_Apr_Unit_8.json'},
        { label: 'Unit 9', link: '../json/ALL_PLUS_Apr_Unit_9.json'},
        { label: 'Unit 10', link: '../json/ALL_PLUS_Apr_Unit_10.json'},
        { label: 'Unit 12', link: '../json/ALL_PLUS_Apr_Unit_12.json'},
        { label: 'Unit 13', link: '../json/ALL_PLUS_Apr_Unit_13.json'},
        { label: 'Unit 14', link: '../json/ALL_PLUS_Apr_Unit_14.json'},
        { label: 'Unit 15', link: '../json/ALL_PLUS_Apr_Unit_15.json'},
    ],
    ALL_PLUS_May: [
        { label: 'Unit 1', link: '../json/ALL_PLUS_May_Unit_1.json'},
        { label: 'Unit 2', link: '../json/ALL_PLUS_May_Unit_2.json'},
        { label: 'Unit 3', link: '../json/ALL_PLUS_May_Unit_3.json'},
        { label: 'Unit 4', link: '../json/ALL_PLUS_May_Unit_4.json'},
        { label: 'Unit 5', link: '../json/ALL_PLUS_May_Unit_5.json'},
        { label: 'Unit 6', link: '../json/ALL_PLUS_May_Unit_6.json'},
        { label: 'Unit 7', link: '../json/ALL_PLUS_May_Unit_7.json'},
        { label: 'Unit 8', link: '../json/ALL_PLUS_May_Unit_8.json'},
        { label: 'Unit 10', link: '../json/ALL_PLUS_May_Unit_10.json'},
        { label: 'Unit 11', link: '../json/ALL_PLUS_May_Unit_11.json'},
        { label: 'Unit 12', link: '../json/ALL_PLUS_May_Unit_12.json'},
        { label: 'Unit 13', link: '../json/ALL_PLUS_May_Unit_13.json'},
        { label: 'Unit 14', link: '../json/ALL_PLUS_May_Unit_14.json'},
        { label: 'Unit 15', link: '../json/ALL_PLUS_May_Unit_15.json'},
        { label: 'Unit 16', link: '../json/ALL_PLUS_May_Unit_16.json'},
    ],
    ALL_PLUS_Jun: [
        { label: 'CNN News', link: '../json/ALL_PLUS_Jun_CNN_News.json'},
        { label: 'Unit 1', link: '../json/ALL_PLUS_Jun_Unit_1.json'},
        { label: 'Unit 2', link: '../json/ALL_PLUS_Jun_Unit_2.json'},
        { label: 'Unit 3', link: '../json/ALL_PLUS_Jun_Unit_3.json'},
        { label: 'Unit 4', link: '../json/ALL_PLUS_Jun_Unit_4.json'},
        { label: 'Unit 5', link: '../json/ALL_PLUS_Jun_Unit_5.json'},
        { label: 'Unit 6', link: '../json/ALL_PLUS_Jun_Unit_6.json'},
        { label: 'Unit 7', link: '../json/ALL_PLUS_Jun_Unit_7.json'},
        { label: 'Unit 9', link: '../json/ALL_PLUS_Jun_Unit_9.json'},
        { label: 'Unit 10', link: '../json/ALL_PLUS_Jun_Unit_10.json'},
        { label: 'Unit 11', link: '../json/ALL_PLUS_Jun_Unit_11.json'},
        { label: 'Unit 12', link: '../json/ALL_PLUS_Jun_Unit_12.json'},
        { label: 'Unit 13', link: '../json/ALL_PLUS_Jun_Unit_13.json'},
        { label: 'Unit 14', link: '../json/ALL_PLUS_Jun_Unit_14.json'},
    ],
    
  };
  